### ISSUE TITLE
BitSwap modelling

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs#10]
The BitSwap protocol is not yet finished. Chances are it won't exactly as described. Still needs modeling + tweaking. (Just a warning for people reading the paper-- that's only large question remaining.)

**Comment by MikeFair** [comment]
Not sure where this should go, but as  I read the paper I really liked that peers are basically given credit scores to determine response behavior; however, if it's not this way already, it'd be nice if the scoring system was somehow modular for different connection sources/methods/device types.

I could see mobile devices getting really bad credit scores due to low/expensive upload bandwidth, small cache size, large request volume (any packets it does find for nearby peers to get credit would be short lived and burn bandwidth).  It'd be nice to somehow express "This device is part of the <somenodegroupid> collection" which includes that 5TB NAS sitting on a couple multihomed 10Gbps links dedicated solely to serving IPFS (not really, but it's likely to chalk up a few credits to offset that mobile leeching) to create a group credit score. ;)

A modular scoring/modeling plugin would allow for playing around with these ideas.

**Comment by Kubuxu** [comment]
The credit system is not implemented yet.

**Comment by diasdavid** [comment]
Follow https://github.com/ipfs/research-bitswap/ for more Bitswap development

//cc @dgrisham
