### ISSUE TITLE
Proposal for deletion mechanism

### ISSUE THREAD

**Issue by randomshinichi** [ipfs/ipfs#156]
As IPFS becomes more popular and is used for storing larger files it might stand to reason that one eventually has to delete data otherwise people might end up storing data that nobody needs or knows about.

But if anybody can delete a file off IPFS, it would make the job of the censors much easier. Hence I propose that only the person who added the file to IPFS in the first place should have the ability/right to send a signal to nodes to delete the no longer needed blocks. This shouldn't be too hard to do with keys and signing mechanisms out there.

**Comment by whyrusleeping** [comment]
ipfs is a trustless system. you can't trust any other node in the network to respect your request that they delete some content. Any other node can hold onto data for as long as they please, and you can't prevent that from happening. Unfortunately (for some), a deletion mechanism is not practical.

**Comment by montagsoup** [comment]
Storing unneeded resources isn't really that much of an issue because unused and unwanted resources will slowly be removed from people's caches. Any wanted data is pinned it so it when be deleted when cleaning out the cache.
As for the practical side of it, it isn't really possible. After you've distributed the file to other people there is nothing forcing them to delete it on the request of the user and nothing keeping them from redistributing it. It's sort of like unsending a letter. You can always sending another letter to tell them to shred the first one, but there's nothing that forces them to do it and they are still able to photocopy it and send it to others as much as they want.

**Comment by peter-mw** [comment]
Doesn't ipfs has remove file function? Like the [add function](https://github.com/ipfs/examples/tree/master/examples/videos#playing-videos) but reverse?

**Comment by jwcrawley** [comment]
Yes, IPFS has a remove function. 

It only modified the local files you have control over. It doesn't hack into other IPFS nodes and remove their files.

**Comment by jbenet** [comment]
Related discussion on the FAQ -- https://github.com/ipfs/faq/issues/9 more there. not here.
