### ISSUE TITLE
Implementation Status Table - File Store

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs#267]
- [ ] File Store (IPFS Pack)
  - [ ] List HTTP endpoints based on http-api-docs (and not http-api-spec)
  - [ ] Add table for CLI
  - [ ] Review and update status in all the endpoints

**Comment by buckle2000** [comment]
May I ask what you mean by "File Store"?

**Comment by diasdavid** [comment]
@lgierth @whyrusleeping is there good documentation on Filestore?

**Comment by kggp1995** [comment]
We're discussing on this matter at #248 

We are a small team from IN working on the filestore. 

Some really tangible papers & approaches are being discussed. Would love to have your inputs there!

**Comment by Stebalien** [comment]
As I don't see this mentioned anywhere here... the *filestore* we're talking about here is a (go-)ipfs feature where go-ipfs can "import" files from the filesystem without importing the data. Basically, we reconstruct the directory tree, indirect blocks, etc. and store these in IPFS however, instead of copying the file *data* into IPFS, we store "pointers" (path, offset, length) to the file data in the filesystem itself.

**Comment by jessicaschilling** [comment]
Closing (stale).
