### ISSUE TITLE
[Proposal] Designing the IPFS Roadmap to Beta 

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs#314]
Here are the notes from the conversation on March 8, formatted as a proposal on a path towards getting an IPFS Roadmap to Beta.

Find them here -- https://docs.google.com/document/d/1JuRWAdF4ACuJIKDaHfuvUeP7J6gRGSwKSbaGzjTLxVo/edit# -- the document is open to comments, feedback is appreciated!

**Comment by Illasera** [comment]
I see a lot of focus on the user and not features...
The user doesn't know what s/he wants, The user desires for solutions to existing problems,

That's why they adopt new technology, since the existing one is facing censorship and inefficient way of distributing data that is also susceptible to attacks; You do not need to add ANYTHING more, Just polish the system as it is (How : Look at the issues that are already opened).

If there is a need for anything more, it will evolve by others, DO NOT try to think ahead, You don't know what the user want, The user doesn't know what s/he wants, Keep on bug-fixing and improve efficiency as described at the opened issues.

**Comment by WolvenMoonstone** [comment]
in terms of having a hard deadline, i'd say no, that sort of thing never seems to work. Maybe just a target date instead when the date is reached we can determine if it is ready.

As for the use case question also probably not it would probably be best to set feature targets and dependencies. like the above comment says do not predict use cases because nobody can predict the amazing potential of IPFS. Even trying has the side effect of limiting its potential, think about Tim-berners-lee or the other internet pioneers, i don't think they could have predicted half what their creation has done. IPFS has even more hidden potential if we allow it.

Advertising? Word of mouth, Mozilla, and maybe a few interviews and demos is all we really need.

**Comment by traverseda** [comment]
>it would probably be best to set feature targets and dependencies. like the above comment says do not predict use cases because nobody can predict the amazing potential of IPFS.

Sure, but as a developer every use-case I think of *doesn't work*. Obviously that's because it's missing some features, but I think ipfs needs to figure out a set of features to prioritize, in order to get any application that is actually useful.

So ipfs could prioritize operating quickly in the browser, so it could be used as a CDN, or otherwise for hosting content. It could alternatively target the linux/sysadmin feature set, which would require things like actually being able to pin large datasets, and use the FUSE filesystem.

Right now it's just kind of impossible to build *anything* useful on ipfs.

**Comment by traverseda** [comment]
@IdeaOutline , take a look at #230

**Comment by daviddias** [comment]
The beta version of the IPFS Project Roadmap now exists on https://github.com/ipfs/roadmap. I welcome you all to review it and share feedback directly on the repo :) Also, you can watch its soft launch at the IPFS Weekly of Dec 17 -- https://github.com/ipfs/team-mgmt/issues/809.
