### ISSUE TITLE
Reuse, or at least cite, OpenAFS technology 

### ISSUE THREAD

**Issue by nwf** [ipfs/ipfs#40]
Many things apparent in the ipfs effort were pioneered a long time ago by the AFS (now OpenAFS) project, including storage location transparency; a global, automatic namespace mounted on the clients; and cross-realm authentication and permission management.  At a minimum, their papers should be studied and cited.

In fact, it might also make sense to reuse much of their work -- ipfs could be implemented as an alternative AFS file server and so reuse all the effort of the AFS file system client kernel and FUSE modules.  (A shim VLDB server may be required for full interoperability, but this is trivial.)  RxRPC is a little long in the tooth at this point but may still provide a good foundation for both client/server and server/server interactions.

I would be happy to answer questions about the above, too; feel free to contact me as well as post here. :)

**Comment by tmagik** [comment]
So this was closed 6 years ago, with a comment about 
> and we'll eventually write our own kernel driver

Does such a thing yet exist, cause I'll use it.

Otherwise, if you know of a distributed filesystem that's had as much adoption and use as AFS, please let me know, as I'm about to go full-on in attempting to bring AFS into the decade where everyone has an IPv6 address, half the world has a linux based phone on their desk (thank you Google), and IPFS is the next "new big thing".

There are some really nice things about IPFS... It seems to me like a great way to package and distributed read-only AFS volumes that you want to share with the rest of the world (like say the Debian archive in AFS, or the gajillion NodeJS modules, or maybe the binaries and everything else for Golang or Rust)

But we still need a kernel module.

**Comment by nwf** [comment]
@tmagik You'll want to look at the `fs/afs` and `net/rxrpc` subsystems in Linux and at https://www.infradead.org/~dhowells/kafs/.  Notably, AuriStor has modernized the Rx and AFS to add IPv6 and modern cryptography ("rxgk") among other things and has supported David Howells' bringing these changes to kAFS.
