### ISSUE TITLE
🌟 Do you want to implement IPFS in a new language, get started here!

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/ipfs#425]
If someone wants to create an IPFS implementation in a new language, the best starting point is to create the supporting libp2p and multiformats modules.  Those modules are useful beyond IPFS and you absolutely need them in order to have a working IPFS implementation in your language.

**Comment by dmgcodevil** [comment]
I would be interested to implement libp2p to Scala using Parapet.

**Comment by jessicaschilling** [comment]
Closing this issue as part of a larger effort to tidy up repos. However, please feel welcome to join in the conversation on the [IPFS Forums](https://discuss.ipfs.io/) to discuss, brainstorm, or get help in implementing IPFS in your favorite language. See you there!

**Comment by Txmike206** [comment]
Sent from Yahoo Mail on Android 
 
  On Thu, Aug 1, 2019 at 4:26 PM, Matt Zumwalt<notifications@github.com> wrote:   
If someone wants to create an IPFS implementation in a new language, the best starting point is to create the supporting libp2p and multiformats modules. Those modules are useful beyond IPFS and you absolutely need them in order to have a working IPFS implementation in your language.
