### ISSUE TITLE
Another name suggestion: Whole Earth File System

### ISSUE THREAD

**Issue by dominictarr** [ipfs/ipfs#7]
Referencing the [Whole Earth Catalogue](http://en.wikipedia.org/wiki/Whole_Earth_Catalog)
This is often considered to be like the internet before the internet, and was an inspiration for many internet pioneers. It also sounds very wholesome and nice. More friendly than the stark "InterPlanetary", which implies span, but not connectedness.

I think this would be a nice association for a p2p cryptosystem!

**Comment by manlea** [comment]
I agree if that is all that is happening, but I think there is stuff going on here. I disagree about the name being trivial, the name, as any marketing people will tell you is vital if people are to actually use it. 
Otherwise it could end up just be a bunch of nerdy guys secret project.,many actually like it that way..

As a comparison I say look at Secondlife and 'Opensim' or Opensimulator..they are basically the same thing, but one is free has less restrictions and should be more popular....why have non-geeks never heard of the latter ? The name Secondlife tells non geeks exactly what it is. A Second life but a virtual one..
Opensimulator tells only nerds, techo's and geeks what it is .. as does 'file system'.

If this is a net it should say so..what sort of net is it ?

Internet ..I get that ..intranet ..I get that !....outernet ? overnet ?  uninet...?  ubernet ? 

I like Ubernet..



If it is a net or internet it should say so..

**Comment by dominictarr** [comment]
oops, getting my bike out of this shed

**Comment by whyrusleeping** [comment]
@manlea the Secondlife vs OpenSim analogy is a poor one. Secondlife has a great marketing team with money behind them, and im pretty sure they have actually ran commercials. OpenSim is nowhere near as pretty, and doesnt appear to have as many features, on top of having almost zero marketing. Its name isnt the issue, Everyone knows whats "the sims" are, and OpenSim draws that immediately to mind for me. 

Users don't need to know what an Operating System is in order to use OS X.

**Comment by ericvicenti** [comment]
Deliberating on the name of the protocol is silly.

Lets focus on making awesome tools for IPFS, which can take a variety of names. Unless there are some killer apps that can rival the likes of Dropbox and git, IPFS will go nowhere.

**Comment by jbenet** [comment]
@ericvicenti this discussion is a year old :) 

I'll close this thread to indicate this better.

> Lets focus on making awesome tools for IPFS, which can take a variety of names. Unless there are some killer apps that can rival the likes of Dropbox and git, IPFS will go nowhere.

agreed! :+1:
