### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by NginUS** [ipfs/ipfs#92]
Hi,

I like this & would like to run a node in a headless Virtualbox instance that runs on my Win10 desktop. Kindly advise as to which distro would be ideal for installation & I'll spin one up & (with your help) get this party started.

Personally, I'd like to host website media using it- for some of my sites.

Please advise.

Thanks,

-N

**Comment by eminence** [comment]
Ubuntu is generally a good choice for people unfamiliar with Linux, but since `ipfs` binary packages are provided, it probably doesn't matter much.

Once you have your VM running, I recommend reading the install guide: http://ipfs.io/docs/install/

And then the getting started guide: http://ipfs.io/docs/getting-started/

If you have any feedback about the documentation, you should leave it here for the community to comment on (and convert into improvements if necessary)
